import nickTwoBadFourU from "eslint-config-nick2bad4u";

import plugin from "./plugin.mjs";

const baseConfig = nickTwoBadFourU.configs.withoutTypefest;

/** @type {import("eslint").Linter.Config[]} */
const config = [
    {
        ignores: [
            ".devcontainer/**",
            "docs/docusaurus/**",
            "docs/docusaurus/site-docs/developer/api/**",
            "docs/docusaurus/static/eslint-inspector/**",
            "docs/docusaurus/static/stylelint-inspector/**",
            "knip.config.ts",
            "plugin.d.mts",
            "test/src/utils/http-client/get-modules/request-get.mjs",
            "tsdown.config.ts",
            "vitest.stryker.config.ts",
        ],
    },

    ...baseConfig,

    {
        files: ["src/**/*.{ts,tsx,mts,cts}"],
        name: "Local JSON Schema Validator",
        plugins: {
            "json-schema-validator": plugin,
        },
    },

    {
        files: ["src/**/*.{ts,tsx,mts,cts}", "test/**/*.{ts,tsx,mts,cts}"],
        name: "Migrated upstream compatibility",
        rules: {
            "@typescript-eslint/ban-ts-comment": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-dynamic-delete": "off",
            "@typescript-eslint/no-invalid-void-type": "off",
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-shadow": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/no-unused-vars": "off",
            "@typescript-eslint/prefer-for-of": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "@typescript-eslint/strict-void-return": "off",
            "@typescript-eslint/switch-exhaustiveness-check": "off",
            "arrow-body-style": "off",
            "capitalized-comments": "off",
            "canonical/filename-no-index": "off",
            "canonical/no-re-export": "off",
            "complexity": "off",
            "import-x/extensions": "off",
            "import-x/max-dependencies": "off",
            "import-x/no-dynamic-require": "off",
            "max-depth": "off",
            "nitpick/no-redundant-vars": "off",
            "nitpick/no-useless-rest": "off",
            "no-barrel-files/no-barrel-files": "off",
            "no-bitwise": "off",
            "no-continue": "off",
            "no-duplicate-imports": "off",
            "no-eq-null": "off",
            "no-plusplus": "off",
            "no-unsanitized/method": "off",
            "no-useless-assignment": "off",
            "listeners/no-inline-function-event-listener": "off",
            "listeners/no-missing-remove-event-listener": "off",
            "n/global-require": "off",
            "n/no-extraneous-import": "off",
            "n/no-process-env": "off",
            "n/no-sync": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "n/prefer-node-protocol": "off",
            "perfectionist/sort-imports": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-named-exports": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-objects": "off",
            "perfectionist/sort-union-types": "off",
            "prefer-named-capture-group": "off",
            "preserve-caught-error": "off",
            "promise/always-return": "off",
            "promise/catch-or-return": "off",
            "regexp/prefer-named-capture-group": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "sdl/no-insecure-url": "off",
            "sdl/no-nonnull-assertion-on-security-input": "off",
            "test-signal/no-empty-async-tests": "off",
            "test-signal/require-assertions": "off",
            "test-signal/require-negative-path": "off",
            "tsdoc-require-2/require": "off",
            "typedoc/require-exported-doc-comment": "off",
            "unicorn/consistent-function-scoping": "off",
            "unicorn/import-style": "off",
            "unicorn/no-array-reverse": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/prefer-module": "off",
            "unicorn/prefer-node-protocol": "off",
            "unicorn/prefer-json-parse-buffer": "off",
            "unicorn/prefer-structured-clone": "off",
            "unicorn/relative-url-style": "off",
            "vitest/no-conditional-tests": "off",
            "vitest/prefer-each": "off",
            "vitest/prefer-expect-assertions": "off",
            "vitest/require-hook": "off",
        },
    },

    {
        files: ["package.json"],
        name: "Migrated package compatibility",
        rules: {
            "depend/ban-dependencies": "off",
            "node-dependencies/no-deprecated": "off",
        },
    },

    {
        files: ["*.mjs"],
        name: "Repository config compatibility",
        rules: {
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "perfectionist/sort-objects": "off",
        },
    },
];

export default config;
