import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
  docs: [
    {
      id: "intro",
      label: "Overview",
      type: "doc",
    },
    {
      id: "getting-started",
      label: "Getting Started",
      type: "doc",
    },
    {
      collapsed: true,
      collapsible: true,
      items: [
        {
          dirName: "developer/api",
          type: "autogenerated",
        },
      ],
      label: "API Reference",
      type: "category",
    },
  ],
} satisfies SidebarsConfig;

export default sidebars;
